package AppViews;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author luisp
 */
public class Partida extends javax.swing.JFrame {

    /**
     * Creates new form ModoDeJuegoPVP
     */
    public Partida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        pnlpvp1 = new javax.swing.JPanel();
        lblpersonavspersona = new javax.swing.JLabel();
        btnevaluarpartida = new javax.swing.JToggleButton();
        btnguardarpartida = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtpnj2 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtpnj1 = new javax.swing.JTextPane();
        pnlpvp2 = new javax.swing.JPanel();
        lbljugador1 = new javax.swing.JLabel();
        rdbtnpiedra1 = new javax.swing.JRadioButton();
        rdbtnpapel1 = new javax.swing.JRadioButton();
        rdbtntijera1 = new javax.swing.JRadioButton();
        pnlpvp3 = new javax.swing.JPanel();
        rdbtntiejra2 = new javax.swing.JRadioButton();
        rdbtnpapel2 = new javax.swing.JRadioButton();
        lbljugador2 = new javax.swing.JLabel();
        rdbtnpiedra2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlpvp1.setName("pnlpvp1"); // NOI18N

        lblpersonavspersona.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblpersonavspersona.setText("PERSONA VS PERSONA");
        lblpersonavspersona.setName("lblpersonavspersona"); // NOI18N

        btnevaluarpartida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnevaluarpartida.setText("EVALUAR PARTIDA");
        btnevaluarpartida.setName("btnevaluarpartida"); // NOI18N
        btnevaluarpartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnevaluarpartidaActionPerformed(evt);
            }
        });

        btnguardarpartida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnguardarpartida.setText("GUARDAR PARTIDA");
        btnguardarpartida.setName("btnguardarpartida"); // NOI18N
        btnguardarpartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarpartidaActionPerformed(evt);
            }
        });

        txtpnj2.setName("txtpnj2"); // NOI18N
        jScrollPane1.setViewportView(txtpnj2);

        txtpnj1.setName("txtpnj1"); // NOI18N
        jScrollPane2.setViewportView(txtpnj1);

        pnlpvp2.setName("pnlpvp2"); // NOI18N

        lbljugador1.setBackground(new java.awt.Color(255, 255, 255));
        lbljugador1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbljugador1.setText(" JUGADOR 1");
        lbljugador1.setName("lbljugador1"); // NOI18N

        rdbtnpiedra1.setText("PIEDRA");
        rdbtnpiedra1.setName("rdbtnpiedra1"); // NOI18N
        rdbtnpiedra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnpiedra1ActionPerformed(evt);
            }
        });

        rdbtnpapel1.setText("PAPEL");
        rdbtnpapel1.setName("rdbtnpapel1"); // NOI18N

        rdbtntijera1.setText("TIEJRA");
        rdbtntijera1.setName("rdbtntijera1"); // NOI18N
        rdbtntijera1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtntijera1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlpvp2Layout = new javax.swing.GroupLayout(pnlpvp2);
        pnlpvp2.setLayout(pnlpvp2Layout);
        pnlpvp2Layout.setHorizontalGroup(
            pnlpvp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbljugador1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
            .addGroup(pnlpvp2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlpvp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnpiedra1)
                    .addComponent(rdbtnpapel1)
                    .addComponent(rdbtntijera1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlpvp2Layout.setVerticalGroup(
            pnlpvp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpvp2Layout.createSequentialGroup()
                .addComponent(lbljugador1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbtnpiedra1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbtnpapel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbtntijera1)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pnlpvp3.setName("pnlpvp3"); // NOI18N

        rdbtntiejra2.setText("-TIEJRA");
        rdbtntiejra2.setName("rdbtntijera2"); // NOI18N

        rdbtnpapel2.setText("-PAPEL");
        rdbtnpapel2.setName("rdbtnpapel2"); // NOI18N

        lbljugador2.setBackground(new java.awt.Color(255, 255, 255));
        lbljugador2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbljugador2.setText("JUGADOR 2");
        lbljugador2.setName("lbljugador2"); // NOI18N

        rdbtnpiedra2.setText("-PIEDRA");
        rdbtnpiedra2.setName("rdbtnpiedra2"); // NOI18N
        rdbtnpiedra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnpiedra2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlpvp3Layout = new javax.swing.GroupLayout(pnlpvp3);
        pnlpvp3.setLayout(pnlpvp3Layout);
        pnlpvp3Layout.setHorizontalGroup(
            pnlpvp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbljugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(rdbtnpiedra2)
            .addComponent(rdbtnpapel2)
            .addComponent(rdbtntiejra2)
        );
        pnlpvp3Layout.setVerticalGroup(
            pnlpvp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpvp3Layout.createSequentialGroup()
                .addComponent(lbljugador2)
                .addGap(5, 5, 5)
                .addComponent(rdbtnpiedra2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnpapel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbtntiejra2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlpvp1Layout = new javax.swing.GroupLayout(pnlpvp1);
        pnlpvp1.setLayout(pnlpvp1Layout);
        pnlpvp1Layout.setHorizontalGroup(
            pnlpvp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpvp1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnlpvp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlpvp1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnevaluarpartida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlpvp1Layout.createSequentialGroup()
                        .addGroup(pnlpvp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlpvp1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnguardarpartida))
                            .addGroup(pnlpvp1Layout.createSequentialGroup()
                                .addComponent(pnlpvp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnlpvp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlpvp1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblpersonavspersona, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        pnlpvp1Layout.setVerticalGroup(
            pnlpvp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpvp1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(lblpersonavspersona)
                .addGap(18, 18, 18)
                .addComponent(btnguardarpartida, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(pnlpvp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlpvp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlpvp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlpvp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnevaluarpartida, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlpvp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlpvp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarpartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarpartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnguardarpartidaActionPerformed

    private void btnevaluarpartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnevaluarpartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnevaluarpartidaActionPerformed

    private void rdbtnpiedra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnpiedra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnpiedra1ActionPerformed

    private void rdbtnpiedra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnpiedra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnpiedra2ActionPerformed

    private void rdbtntijera1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtntijera1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtntijera1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnevaluarpartida;
    private javax.swing.JButton btnguardarpartida;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbljugador1;
    private javax.swing.JLabel lbljugador2;
    public javax.swing.JLabel lblpersonavspersona;
    private javax.swing.JPanel pnlpvp1;
    private javax.swing.JPanel pnlpvp2;
    private javax.swing.JPanel pnlpvp3;
    private javax.swing.JRadioButton rdbtnpapel1;
    private javax.swing.JRadioButton rdbtnpapel2;
    private javax.swing.JRadioButton rdbtnpiedra1;
    private javax.swing.JRadioButton rdbtnpiedra2;
    private javax.swing.JRadioButton rdbtntiejra2;
    private javax.swing.JRadioButton rdbtntijera1;
    private javax.swing.JTextPane txtpnj1;
    private javax.swing.JTextPane txtpnj2;
    // End of variables declaration//GEN-END:variables

    public void setPuntajes(int a, int b){
        this.txtpnj1.setText(a + " puntos");
        this.txtpnj2.setText(b + " puntos");
    }

    public void getJugadaA(){
        int v=0 ;
        if(rdbtnpapel1.isSelected()){
            v = 1;
        }else if(rdbtnpiedra1.isSelected()){
            v = 2;
        }else if(rdbtntijera1.isSelected()){
            v = 2;
        }
    }


}
